### ISSUE TITLE
mro / with grapes against HTTP nexus with route (configured to redirect to https) fails with 302 - cannot resolve

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#201]
**Describe the bug**
If the nexus URL in the jenkins DC points to HTTP while the route on nexus is configured to to a redirect to HTTPS - grape lookup  / download will fail.

**To Reproduce**
1. Configure jenkins DC nexus url against HTTP (not https) of nexus
2. run MRO enabled library - this will fail (java.lang.RuntimeException: Error grabbing Grapes -- [unresolved dependency: org.yaml#snakeyaml;1.24: not found])

**Expected behavior**
Grapes lookup against configured NEXUS url works ..

**Affected version (please complete the following information):**
 - OpenDevStack [1.2.x]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
org.jenkinsci.plugins.workflow.cps.CpsCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [unresolved dependency: org.yaml#snakeyaml;1.24: not found]

java.lang.RuntimeException: Error grabbing Grapes -- [unresolved dependency: org.yaml#snakeyaml;1.24: not found]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at groovy.grape.GrapeIvy.getDependencies(GrapeIvy.groovy:424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
```

**Additional context**
https://github.com/opendevstack/ods-core/blob/master/nexus/ocp-config/route.yml#L17

should allow both - fix: `insecureEdgeTerminationPolicy: Allow`

**Comment by clemensutschig** [comment]
@gerardcl  fya
