### ISSUE TITLE
app wants to create jira components for project without bugtracker space

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-core#295]
**Describe the bug**

**To Reproduce**
1. create a new project without creating jira and confluence projects
2. Modifiy project and add a new component to it
3. See error in log: the app tries to create jira components.

**Expected behavior**
Application should not create jira component, because project has no jira project created.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack current master

**Log Output**
```
2019-12-02 09:34:33 ERROR o.o.provision.util.rest.RestClient - Call failed: 
org.opendevstack.provision.util.exception.HttpException: Could not POST > http://192.168.56.31:8080/rest/api/latest/component : {"errorMessages":["No project could be found with key 'TST10'."],"errors":{}} Errorcode: 404
	at org.opendevstack.provision.util.rest.RestClient.execute(RestClient.java:51)
	at org.opendevstack.provision.services.JiraAdapter.createComponentsForProjectRepositories(JiraAdapter.java:486)
	at org.opendevstack.provision.controller.ProjectApiController.createDeliveryChain(ProjectApiController.java:411)
	at org.opendevstack.provision.controller.ProjectApiController.updateProject(ProjectApiController.java:278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:919)
```

**Additional context**

**Comment by stefanlack** [comment]
Issue was created in wrong repository
