### ISSUE TITLE
sonarqube build failing with username / pw required: https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.7.3.zip 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#32]
+ mkdir /opt
--
  | + cd /opt
  | + wget -O sonarqube.zip --no-verbose https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.7.3.zip
  | Username/Password Authentication Failed.
  | Removing intermediate container 0aba9b10abee

Get the LTS (Long-term Support): SonarQube 6.7.x  (that's why I guess)

![image](https://user-images.githubusercontent.com/40628552/46600413-5dd1f900-caea-11e8-850e-be188e8ae2d4.png)

**Comment by clemensutschig** [comment]
bubble to 7.3 ...

2018.10.08 09:50:25 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
--
  | java.lang.IllegalStateException: Fail to load plugin Crowd [crowd]
  | at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
  | at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
  | at org.sonar.server.platform.Platform.start(Platform.java:211)
  | at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
  | at org.sonar.server.platform.Platform.access$500(Platform.java:46)
  | at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
  | at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
  | at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
  | at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.NoClassDefFoundError: org/sonar/api/ServerExtension
  | at java.lang.ClassLoader.defineClass1(Native Method)
  | at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  | at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  | at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)


seems the basic plugins don't work anymore ..

**Comment by clemensutschig** [comment]
update: 
a) scala plugin does NOT exist anymore :( 
b) crowd plugin expects now /crowd in the crowd url

**Comment by clemensutschig** [comment]
assigning to myself . as I already working on it.
