### ISSUE TITLE
jenkins script approval incomplete

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-core#416]
**Describe the bug**
When jenkins is going to create and deploy an image, the error
`Scripts not permitted to use method java.util.regex.Matcher find` occurs.

**To Reproduce**
1. Execute build pipelne
2. See error on step _Build Openshift Image_

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [2.x]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method java.util.regex.Matcher find
	at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectMethod(StaticWhitelist.java:175)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:159)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:156)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:160)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at stageStartOpenshiftBuild.call(/var/lib/jenkins/jobs/prov-cd/jobs/prov-cd-ods-provisioning-app-production/builds/1/libs/ods-library/vars/stageStartOpenshiftBuild.groovy:20)
```

**Question**
Allow execution of `Matcher find` may be dangerous (see https://rules.sonarsource.com/java/tag/owasp/RSPEC-4784), but as long as the input to the matcher is controlled, I is save.

Should we add the method to https://github.com/opendevstack/ods-core/blob/master/jenkins/master/configuration/scriptApproval.xml ?

**Comment by michaelsauter** [comment]
IMHO we could add it. However, there seems to be some odd behaviour related to the Jenkins version in use. Newer versions do not show this problem. What is your Jenkins version? Are you using the RedHat based image?

**Comment by stefanlack** [comment]
We are using Jenkins 2.164.2.
Image is based on openshift/jenkins-2-centos7:v3.11

**Comment by michaelsauter** [comment]
Ah that is old. Hmm. 2.176.3 does not have that issue ....

**Comment by clemensutschig** [comment]
@stefanlack  - did you try with latest 2.x ODS? ... we have not seen any issues ... (and btw .. we flipped much of this to be the global shared lib now)

**Comment by michaelsauter** [comment]
I think we can close this. Please reopen if you need.
