### ISSUE TITLE
[bug]: failed to run script file: ods-mro-jenkins-shared-library.groovy

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-core#552]
## Describe the bug
Jenkins is throwing a warning during the deployment process. 

### OpenShift

1. Go to `hugo-cd`
2. Trigger an new deployment of jenkins 
3. Go to the `Logs` tab of running jenkins pod
4. See warning

## Expected behavior

Deployment without warnings / errors / stack trace

## Screenshots

![image](https://user-images.githubusercontent.com/17799657/81820620-21217b80-9531-11ea-8f03-383f3f165de8.png)

## Affected version

- **OpenShift:** 3.11
- **OpenDevStack:** 2.x

## Log Output

```
[...]
DEBUG: Adding MRO build shared lib
May 13, 2020 1:38:53 PM jenkins.util.groovy.GroovyHookScript execute
WARNING: Failed to run script file:/var/lib/jenkins/init.groovy.d/ods-mro-jenkins-shared-library.groovy
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at java_util_List$add$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at ods-mro-jenkins-shared-library.run(ods-mro-jenkins-shared-library.groovy:75)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1095)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[...]
```

## Additional Info

Ref: #316

**Comment by clemensutschig** [comment]
@SimonGolms  - this is mega weird,... we have never seen this - what happens if you try again? same?

**Comment by SimonGolms** [comment]
@clemensutschig yes, the same thing all the time.

**Comment by clemensutschig** [comment]
Hurray - I can reproduce this ... 

```
    List listYes = Collections.EMPTY_LIST
    println (listYes.size == [])
    listYes << "test"
```
yields .. 
```
true
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.leftShift(DefaultGroovyMethods.java:12421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.leftShift(DefaultGroovyMethods.java:12438)
	at org.codehaus.groovy.runtime.dgm$386.invoke(Unknown Source)
```
good lord - groovy at work ... :(

**Comment by clemensutschig** [comment]
As I wrote you - can you try create a new pvc and replace the existing reference in the DC with this one ... and then try again. Thank you
