### ISSUE TITLE
Support for http proxy for Nexus and Jenkins master

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#637]
**Is your feature request related to a problem?**
In a corp environment there is usually a proxy to filter inet traffic. While all other components already support a proxy - Nexus and Jenkins master dont - which means no updates, no market place

**Describe the solution you'd like**
Full support for http proxy

**Comment by michaelsauter** [comment]
SQ is fixed in https://github.com/opendevstack/ods-core/pull/570.

**Comment by michaelsauter** [comment]
For Nexus: https://github.com/sonatype-nexus-community/nexus-scripting-examples/blob/master/complex-script/core.groovy. Question if we could get the `HTTP_PROXY` automatically (it is in the pod).

**Comment by clemensutschig** [comment]
https://github.com/Accenture/adop-nexus/blob/master/resources/conf/setup_http_proxy.groovy

**Comment by clemensutschig** [comment]
@michaelsauter 
```
Caused by: java.lang.SecurityException: Importing [java.lang.System] is not allowed
	at org.codehaus.groovy.control.customizers.SecureASTCustomizer.assertImportIsAllowed(SecureASTCustomizer.java:677)
	at org.codehaus.groovy.control.customizers.SecureASTCustomizer.access$800(SecureASTCustomizer.java:183)
	at org.codehaus.groovy.control.customizers.SecureASTCustomizer$SecuringCodeVisitor.assertExpressionAuthorized(SecureASTCustomizer.java:765)
	... 36 more

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1107)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:279)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:236)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:335)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:157)
	... 16 common frames omitted
``` .... when calling system.getenv ...
