### ISSUE TITLE
ODS CI AMI build of 3.x fails due NPE in orchestration stage  

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#947]
It looks like last change in `ods-jenkins-shared-lib` (https://github.com/opendevstack/ods-jenkins-shared-library/tree/3.x) broke the build.

```
[0;32m    amazon-ebs: [docgen-odsverify-DTP] Creating document of type 'DTP' for project 'odsverify' in phase 'Build' and stage 'POST_START'[0m
[0;32m    amazon-ebs: expected to call org.ods.orchestration.usecase.LeVADocumentUseCase.invokeMethod but wound up catching org.ods.orchestration.usecase.LeVADocumentUseCase.createDTP; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: WARN: Error: Creating document of type 'DTP' for project 'odsverify' in phase 'Build' and stage 'POST_START' has failed: Cannot invoke method getDocGenFormat() on null object.[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: Failed in branch orchestration[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: WARN: null[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: Failed in branch golang[0m
[0;32m    amazon-ebs: [Pipeline] // parallel[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: Failed in branch Build[0m
[0;32m    amazon-ebs: [Pipeline] // parallel[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: WARN: Error occured within the orchestration pipeline: Error: Creating document of type 'DTP' for project 'odsverify' in phase 'Build' and stage 'POST_START' has failed: Cannot invoke method getDocGenFormat() on null object.[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: [Build] **** ENDED orchestration stage **** (took 1690 ms)[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // stage[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // withEnv[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: [ods-mro-pipeline] **** ENDED orchestration pipeline **** (took 35279 ms)[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // podTemplate[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // node[0m
[0;32m    amazon-ebs: [Pipeline] End of Pipeline[0m
[0;32m    amazon-ebs: java.lang.NullPointerException: Cannot invoke method getDocGenFormat() on null object[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.usecase.LeVADocumentUseCase.createDTP(LeVADocumentUseCase.groovy:212)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:304)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:154)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:300)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:288)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.BuildStage.run(BuildStage.groovy:66)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.Stage.executeInParallel(Stage.groovy:76)[0m
[0;32m    amazon-ebs: 	at ___cps.transform___(Native Method)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:84)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:78)[0m
[0;32m    amazon-ebs: 	at jdk.internal.reflect.GeneratedMethodAccessor227.invoke(Unknown Source)[0m
[0;32m    amazon-ebs: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0;32m    amazon-ebs: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)[0m
[0;32m    amazon-ebs: Also:   org.jenkinsci.plugins.workflow.steps.FlowInterruptedException[0m
[0;32m    amazon-ebs: 		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.cancel(CpsBodyExecution.java:253)[0m
[0;32m    amazon-ebs: 		at org.jenkinsci.plugins.workflow.steps.BodyExecution.cancel(BodyExecution.java:76)[0m
[0;32m    amazon-ebs: 		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStepExecution.stop(ParallelStepExecution.java:67)[0m
[0;32m    amazon-ebs: 		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.checkAllDone(ParallelStep.java:147)[0m
[0;32m    amazon-ebs: 		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.onFailure(ParallelStep.java:134)[0m
[0;32m    amazon-ebs: 		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:361)[0m
[0;32m    amazon-ebs: 		at com.cloudbees.groovy.cps.impl.ValueBoundContinuation.receive(ValueBoundContinuation.java:21)[0m
[0;32m    amazon-ebs: 		at com.cloudbees.groovy.cps.Block$Noop.eval(Block.java:30)[0m
[0;32m    amazon-ebs: Caused: java.lang.IllegalStateException: Error: Creating document of type 'DTP' for project 'odsverify' in phase 'Build' and stage 'POST_START' has failed: Cannot invoke method getDocGenFormat() on null object.[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:306)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:154)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:300)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:288)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.BuildStage.run(BuildStage.groovy:66)[0m
[0;32m    amazon-ebs: 	at org.ods.orchestration.Stage.executeInParallel(Stage.groovy:76)[0m
[0;32m    amazon-ebs: 	at ___cps.transform___(Native Method)[0m
[0;32m    amazon-ebs: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[0m
[0;32m    amazon-ebs: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[0m
[0;32m    amazon-ebs: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[0m
[0;32m    amazon-ebs: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)[0m
[0;32m    amazon-ebs: 	at jdk.internal.reflect.GeneratedMethodAccessor228.invoke(Unknown Source)[0m
[0;32m    amazon-ebs: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0;32m    amazon-ebs: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)[0m
[0;32m    amazon-ebs: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m
[0;32m    amazon-ebs: 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)[0m
[0;32m    amazon-ebs: 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)[0m
[0;32m    amazon-ebs: 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)[0m
[0;32m    amazon-ebs: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)[0m
[0;32m    amazon-ebs: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m
[0;32m    amazon-ebs: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m
[0;32m    amazon-ebs: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m
[0;32m    amazon-ebs: 	at java.base/java.lang.Thread.run(Thread.java:834)[0m
[0;32m    amazon-ebs: Finished: FAILURE[0m
[0;32m    amazon-ebs: Master (code) 2nd build with golang for releasemanager returned:[0m
[0;32m    amazon-ebs: [[0m
[0;32m    amazon-ebs:   {[0m
[0;32m    amazon-ebs:     "stage": "Init",[0m
[0;32m    amazon-ebs:     "status": "SUCCESS"[0m
[0;32m    amazon-ebs:   },[0m
[0;32m    amazon-ebs:   {[0m
[0;32m    amazon-ebs:     "stage": "Build",[0m
[0;32m    amazon-ebs:     "status": "FAILED"[0m
[0;32m    amazon-ebs:   }[0m
[0;32m    amazon-ebs: ][0m
[0;32m    amazon-ebs:     jenkinsfile_test.go:228: Jenkins stages mismatch for build of releasemanager (-want +got):[0m
[0;32m    amazon-ebs:           strings.Join({[0m
[0;32m    amazon-ebs:           	... // 5 identical lines[0m
[0;32m    amazon-ebs:           	"  {",[0m
[0;32m    amazon-ebs:           	`    "stage": "Build",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "odsPipeline start",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Check Format",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Lint",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Unit Test",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Build",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "SonarQube Analysis",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Build OpenShift Image",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Deploy to OpenShift",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "odsPipeline finished",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Deploy",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Test",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Release",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         - 	"  },",[0m
[0;32m    amazon-ebs:         - 	"  {",[0m
[0;32m    amazon-ebs:         - 	`    "stage": "Finalize",`,[0m
[0;32m    amazon-ebs:         - 	`    "status": "SUCCESS"`,[0m
[0;32m    amazon-ebs:         + 	`    "status": "FAILED"`,[0m
[0;32m    amazon-ebs:           	"  }",[0m
[0;32m    amazon-ebs:           	"]",[0m
[0;32m    amazon-ebs:           	"",[0m
[0;32m    amazon-ebs:           }, "\n")[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: --- FAIL: TestVerifyOdsQuickstarterProvisionThruProvisionApi (388.64s)[0m
[0;32m    amazon-ebs: FAIL[0m
[0;32m    amazon-ebs: FAIL	github.com/opendevstack/ods-quickstarters/tests/release-manager	388.656s[0m
[0;32m    amazon-ebs: ?   	github.com/opendevstack/ods-quickstarters/tests/utils	[no test files][0m
[0;32m    amazon-ebs: FAIL[0m
[1;31m==> amazon-ebs: make: *** [test] Error 1[0m
2021/02/01 15:39:05 packer-builder-amazon-ebs plugin: [ERROR] Remote command exited with '2': /tmp/script_4865.sh  --branch 3.x
```

**Comment by stitakis** [comment]
@metmajer since you merged the last PR in `ods-jenkins-shared-lib` (branch 3.x) I've assigned this to you for further investigation. Please let me know if you need any help investigating this.

**Comment by metmajer** [comment]
@stitakis this is too little information to do something with it. Please connect with the team internally to explain how you set up the project.

**Comment by clemensutschig** [comment]
martin, we have a fully automated testcase - that fails, so there is really a lot of context to diagnose?!

https://github.com/opendevstack/ods-jenkins-shared-library/blob/3.x/src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy#L212

I bet it's because there is NO jira ... :)

**Comment by metmajer** [comment]
Closed via https://github.com/opendevstack/ods-jenkins-shared-library/pull/573
