### ISSUE TITLE
ODS AMI build fails for master branch due to an error in orchestration pipeline

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-core#959]
**Describe the bug**
ODS AMI build fails due to
`amazon-ebs: groovy.lang.MissingPropertyException: No such property: repoName for class: org.ods.component.Pipeline

```
[0;32m    amazon-ebs: Fetching upstream changes from http://bitbucket.odsbox.lan:7990/scm/opendevstack/ods-jenkins-shared-library.gitESC[0m
ESC[0;32m    amazon-ebs: using GIT_ASKPASS to set credentials unitt-cd-cd-user-with-passwordESC[0m
ESC[0;32m    amazon-ebs:  > git fetch --no-tags --progress http://bitbucket.odsbox.lan:7990/scm/opendevstack/ods-jenkins-shared-library.git +refs/heads/*:refs/remotes/origin/*ESC[0m
ESC[0;32m    amazon-ebs: Checking out Revision daa9205519581b25f43982e63c5844f4e44ce4ef (latest)ESC[0m
ESC[0;32m    amazon-ebs:  > git config core.sparsecheckout # timeout=10ESC[0m
ESC[0;32m    amazon-ebs:  > git checkout -f daa9205519581b25f43982e63c5844f4e44ce4efESC[0m
ESC[0;32m    amazon-ebs: Commit message: "find repoName dynamically (#582)"ESC[0m
ESC[0;32m    amazon-ebs: First time build. Skipping changelog.ESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] Start of PipelineESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] nodeESC[0m
ESC[0;32m    amazon-ebs: Running on Jenkins in /var/lib/jenkins/jobs/unitt-cd/jobs/unitt-cd-run-unitt-monorepo-iq-test-unitt-master/workspaceESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] {ESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] shESC[0m
ESC[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': labelESC[0m
ESC[0;32m    amazon-ebs: + git config --get remote.origin.urlESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] shESC[0m
ESC[0;32m    amazon-ebs: WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': labelESC[0m
ESC[0;32m    amazon-ebs: + oc -n unitt-cd get bc/run-unitt-monorepo-iq-test-unitt-master -o 'jsonpath={.spec.source.git.uri}'ESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] }ESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] // nodeESC[0m
ESC[0;32m    amazon-ebs: [Pipeline] End of PipelineESC[0m
ESC[0;32m    amazon-ebs: groovy.lang.MissingPropertyException: No such property: repoName for class: org.ods.component.PipelineESC[0
ESC[0;32m    amazon-ebs:        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)ESC[0m
ESC[0;32m    amazon-ebs:        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)ESC[0m
ESC[0;32m    amazon-ebs:        at org.ods.component.Pipeline.amendProjectAndComponentFromOrigin(Pipeline.groovy:395)ESC[0m
ESC[0;32m    amazon-ebs:        at ___cps.transform___(Native Method)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)ESC[0m
ESC[0;32m    amazon-ebs:        at jdk.internal.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)ESC[0m
ESC[0;32m    amazon-ebs:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)ESC[0m
ESC[0;32m    amazon-ebs:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.Next.step(Next.java:83)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)ESC[0m
ESC[0;32m    amazon-ebs:        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)ESC[0m
ESC[0;32m    amazon-ebs:        at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)ESC[0m
ESC[0;32m    amazon-ebs:        at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)ESC[0m
ESC[0;32m    amazon-ebs:        at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)ESC[0m
ESC[0;32m    amazon-ebs:        at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)ESC[0m
ESC[0;32m    amazon-ebs:        at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)ESC[0m
ESC[0;32m    amazon-ebs:        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)ESC[0m
ESC[0;32m    amazon-ebs:        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)ESC[0m
ESC[0;32m    amazon-ebs:        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)ESC[0m
ESC[0;32m    amazon-ebs:        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)ESC[0m
ESC[0;32m    amazon-ebs:        at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)ESC[0m
ESC[0;32m    amazon-ebs:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)ESC[0m
ESC[0;32m    amazon-ebs:        at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)ESC[0m
ESC[0;32m    amazon-ebs:        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)ESC[0m
ESC[0;32m    amazon-ebs:        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)ESC[0m
ESC[0;32m    amazon-ebs:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)ESC[0m
ESC[0;32m    amazon-ebs:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)ESC[0m
ESC[0;32m    amazon-ebs:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)ESC[0m
ESC[0;32m    amazon-ebs:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)ESC[0m
ESC[0;32m    amazon-ebs:        at java.base/java.lang.Thread.run(Thread.java:834)ESC[0m
ESC[0;32m    amazon-ebs: Finished: FAILUREESC[0m

```

**Comment by clemensutschig** [comment]
closing - this is fixed thru https://github.com/opendevstack/ods-jenkins-shared-library/pull/584
