### ISSUE TITLE
Latest master build fails with: Could not instantiate {delegate={$class=AnsiColorBuildWrapper, colorMapName=XTerm}}

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#991]
**Describe the bug**
```
build of jenkins master:
------------------
[0;32m    amazon-ebs: Downloading plugin: ansicolor from https://updates.jenkins.io/download/plugins/ansicolor/0.7.0/ansicolor.hpi[0m
[0;32m    amazon-ebs: --------------------------------------------------------------------------------[0m
[0;32m    amazon-ebs: Total                                               13 MB/s | 3.1 MB  00:00[0m
[0;32m    amazon-ebs: Running transaction check[0m
[0;32m    amazon-ebs: Running transaction test[0m
[0;32m    amazon-ebs: Transaction test succeeded[0m
[0;32m    amazon-ebs: Running transaction[0m
[0;32m    amazon-ebs: Downloading plugin: ansicolor-plugin from https://updates.jenkins.io/download/plugins/ansicolor-plugin/0.7.0/ansicolor-plugin.hpi[0m
......
[0;32m    amazon-ebs: [91mFailed to download plugin: ansicolor or ansicolor-plugin[0m

----------------------------
and later for each quickstarter:

[0;32m    amazon-ebs: WARN: Error during ODS component pipeline setup: java.lang.IllegalArgumentException: Could not instantiate {delegate={$class=AnsiColorBuildWrapper, colorMapName=XTerm}} for org.jenkinsci.plugins.workflow.steps.CoreWrapperStep: java.lang.UnsupportedOperationException: no known implementation of class jenkins.tasks.SimpleBuildWrapper is named AnsiColorBuildWrapper[0m
[0;32m    amazon-ebs: [Pipeline] echo[0m
[0;32m    amazon-ebs: Cannot set Bitbucket build status to 'FAILED' because required data is missing![0m
[0;32m    amazon-ebs: [Pipeline] emailext[0m
[0;32m    amazon-ebs: An attempt to send an e-mail to empty list of recipients, ignored.[0m
[0;32m    amazon-ebs: [Pipeline] }[0m
[0;32m    amazon-ebs: [Pipeline] // node[0m
[0;32m    amazon-ebs: [Pipeline] End of Pipeline[0m
[0;32m    amazon-ebs: java.lang.UnsupportedOperationException: no known implementation of class jenkins.tasks.SimpleBuildWrapper is named AnsiColorBuildWrapper[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.structs.describable.DescribableModel.resolveClass(DescribableModel.java:549)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:473)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:269)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)[0m
[0;32m    amazon-ebs: 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)[0m
[0;32m    amazon-ebs: 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)[0m
[0;32m    amazon-ebs: Caused: java.lang.IllegalArgumentException: Could not instantiate {delegate={$class=AnsiColorBuildWrapper, colorMapName=XTerm}} for org.jenkinsci.plugins.workflow.steps.CoreWrapperStep[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)[0m
[0;32m    amazon-ebs: 	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:269)[0m
```

**To Reproduce**
Run backbone CI for latest master

**Expected behavior**
Clean build

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [master]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
see above
```

**Comment by clemensutschig** [comment]
@gerardcl  can you take a look at this?!

**Comment by clemensutschig** [comment]
I played with the url - seems there is a pretty bad hickup with the updatecenter?! ... hmmm

**Comment by gerardcl** [comment]
I will take a look, should we move this issue on the ods-quickstarters though?

**Comment by clemensutschig** [comment]
Works again..  closing
